name: bwaindex
description: bwa index of final_assembly.fasta
keywords:
  - bwa
  - indexing
tools:
  - bwa:
      description: |
        BWA is a software package for mapping DNA sequences against
        a large reference genome, such as the human genome.
      homepage: http://bio-bwa.sourceforge.net/
      documentation: http://www.htslib.org/doc/samtools.html
      arxiv: arXiv:1303.3997
      licence: ["GPL-3.0-or-later"]
input:
  - batch:
      type: value
      description: declare batch 
  - fasta:
      type: file
      description: Input genome fasta file
output:
  - index:
      type: file
      description: BWA genome index files
      pattern: "*.{fasta,sa,amb,ann,pac,bwt}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@daniel.liu"

